---
# install the front
- name: Installation du serveur
  hosts: front
  remote_user: vagrant
  become: yes
  tasks:
  - include_vars:
     file: vars.yml  
  - include_role:
      name: ansistrano.deploy    